# Generated by Django 4.0.3 on 2022-04-14 11:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallino_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=14, null=True)),
                ('mslink_dmr', models.FloatField()),
                ('fname', models.CharField(max_length=32, null=True)),
                ('mapid', models.BigIntegerField()),
                ('name', models.CharField(max_length=30, null=True)),
                ('width', models.FloatField()),
                ('bound', models.BigIntegerField()),
                ('operation_field', models.CharField(max_length=17, null=True)),
                ('recno', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
