# Generated by Django 4.0.3 on 2022-04-14 11:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahallino_api', '0002_roads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=32639),
        ),
    ]
