# Generated by Django 4.0.3 on 2022-04-14 14:33

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mahallino_api', '0003_alter_roads_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('title', models.CharField(max_length=50, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
