# Generated by Django 4.0.3 on 2022-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallino_api', '0005_aludegi_brt_busy_cng_fire_fuel_gym_hospital_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brt',
            name='line',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
