# Generated by Django 4.0.3 on 2022-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0002_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='createddat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
