# Generated by Django 4.0.3 on 2022-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0003_alter_bus_createddat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='updatedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
